workflows:
  flutter_build:
    name: Flutter Build
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - name: Install Flutter
        script: flutter pub global activate flutter
      - name: Flutter clean
        script: flutter clean
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter format
        script: flutter format --set-exit-if-changed .
      - name: Flutter test
        script: flutter test
      - name: Build APK
        script: flutter build apk
      - name: Build iOS
        script: flutter build ios --release --no-codesign
        artifact_paths:
          - build/ios/iphoneos/Runner.app

app:
  android:
    build_mode: release
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
  ios:
    build_mode: release
    artifacts:
      - build/ios/ipa/Runner.ipa
