workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # Add scripts here
    artifacts:
      - build/app/outputs/apk/*.apk
      - build/app/outputs/ipa/*.ipa
    publishing:
      email:
        recipients:
          - educatalan02@gmail.com
        
