workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # Add scripts here
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - educatalan02@gmail.com
        subject: "Nueva versi贸n de la aplicaci贸n"
        body: "Se ha generado una nueva versi贸n de la aplicaci贸n. Adjunto se encuentran los archivos APK e IPA."
        attachments:
          - build/**/outputs/**/*.apk
          - build/ios/ipa/*.ipa
