workflows:
  default-workflow:
    name: Default workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter pub get
      - flutter build apk --release
      - flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - educatalan02@gmail.com
        
